theme: jekyll-theme-modernist
title: "WELCOME TO NEWLIFE DIVINE'S HOMEPAGE!"
description: This is my trial page on website creation and management. Feel free to check here regularly for science fictions, gospel messages and other academic information
#THE GOSPEL SCHEME
